version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Update bundler
          command: bundle update --bundler
      - ruby/bundle-install
      - run:
          name: Set up Webpack
          command: rails webpack:install
      - run:
          name: Set up test database
          command: rails db:test:prepare
