version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  heroku: circleci/heroku@1.2.3 # Invoke the Heroku orb

workflows:
  build_and_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install correct bundler
          command: gem install bundler -v $(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -1 | tr -d " ")
      - ruby/bundle-install
      - run:
          name: Set up Webpacker
          command: bin/rails webpacker:install
      - run:
          name: Set up test database
          command: bin/rails db:test:prepare
      - run:
          name: Run tests
          command: bin/rails spec
